### PR TITLE
allows a user to sort articles

### PR DESCRIPTION
**Pull request by MFStevenson**

### CODE REVIEW

**Review by nc-modou — COMMENTED** [review]
Great work so far! The sort by works really smoothly - but there's a couple details that I think you missed.
- You should have articles sorted by default (to date descending unless otherwise specified in plan), instead of just null in the place of the sort
- You should sort by date/votes/comment count because it makes sense as to how they're being sorted (since they are numbers), not as much need to sort by author and title since they're words

Consider the feedback then resubmit a PR please, the merge is right around the corner 👍

**Review by popatre — CHANGES_REQUESTED** [review]
The sorting doesnt seem to work on the topic pages

There also a slight UX issue when changing the topic, on a slow connection, it looks like nothings happening, then suddenly changes. (this is the previous ticket, but thought you'd want to know)

https://jam.dev/c/7cdc5e8d-724c-42ac-bd5d-c5c4b4c6263b

**Review by popatre — CHANGES_REQUESTED** [review]
Seems to sort on topics now, however theres one bug.

- [ ] Your drop down boxes dont say the option thats been selected after pressing sort. It looks like the sort by the right thing, but the text resets to date and descending. It should say the current option they're selected to sort by

**Review by ghost — APPROVED** [review]
Much better! I was worried sorting by votes wasn't working but it turned out none of the articles in that topic had any votes...

**Pull request merged**
